rabbit1:
  image: "rabbitmq:3.9-management"
  hostname: "rabbit1"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq1"
  volumes:
    - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"